---
- name: Copy file to all servers
  hosts: all
  become: yes


  tasks:
   - name: Copy index.html
     copy:
       src: /usr/src/dba/index.html
       dest: /tmp/sample.txt
       owner: root
       group: root
       mode: '0644'