apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: volume-share-nautilus
spec:
  containers:
  - name: volume-container-nautilus-1
    image: debian:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/official
  - name: volume-container-nautilus-2
    image: debian:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/cluster
  volumes:
  - name: volume-share
    emptyDir:


# Official Documentation: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# Volumes Official Documentation: https://kubernetes.io/docs/concepts/storage/volumes/
# Shell command validation: validation-shell.sh